tasks:
  - command: |
      code --install-extension redhat.java@1.22.1
      code --install-extension vscjava.vscode-java-debug
      sleep 5
      code --install-extension revaturePro.revature-labs

  - command: |
      code --uninstall-extension vscjava.vscode-java-test || true
      sleep 5

  - command: |
      chmod 600 ~/.ssh/id_rsa
      chmod 644 ~/.ssh/id_rsa.pub
      ssh-keyscan github.com >> ~/.ssh/known_hosts

  - command: |
      git remote set-url origin git@github.com:dev-atobatele/dev-atobatele-pep-spring-project.git
      sed "s/\r$//" commit-command.sh | bash
spring.threads.virtual.enabled: true
